### ISSUE TITLE
URL used in code returns 404

### ISSUE THREAD

**Issue by quadrplax** [mutantmonkey/youtube-remote#1]
There is a URL referenced in the code which returns a 404 error, preventing it from working:  

https://www.youtube.com/api/lounge/pairing/get_screen  

Without this part of the code working, you cannot pair a device, thus making this code unusable.

**Comment by mutantmonkey** [comment]
This project is no longer maintained. Please feel free to fork it and modify it as you see fit.

**Comment by quadrplax** [comment]
I would do that if I knew how to fix it, but I can't find anything about YouTube's TV API in the documentation.

________________________________
